### ISSUE TITLE
Создать сущность "Марка машин"

### ISSUE THREAD

**Issue by mubat** [andrkyn/autoandev#2]
Необходимо создать все объекты, которые бы описывали вышеуказанную сущность.
Нужно описать миграцию, которая бы создавала таблицу в базе.
При помощи генератора создать модель, контроллер, view файлы.
Добавить ссылку в главное меню админки.

Реализовать в отдельной ветке.

**Comment by andrkyn** [comment]
Всё выполнил по вышеуказанным пунктам, добавил ветку dev. В главном меню ссылка admin.

**Comment by mubat** [comment]
Миграции
----------------
- колонкам стоит ставить `notNull()` только когда действительно значение должно быть указано, то есть по минимуму использовать эту директиву. А остальным нужным полям проставлять правило _required_.  Таким образом в дальнейшем можно с лёгкостью манипулировать правилами.
```php
        $this->createTable('brand', [
            'id' => $this->primaryKey(),
            'name' => $this->string(30)->notNull(), // нет необходимости указывать 'notNull' здесь. Достаточно будет прописать правило
            'slug' => $this->string(30)->notNull()->unique(),
            'img' => $this->string()->notNull(), // изображения я обычно не ставлю обязательными в базе. В ходе разарботки может отпасть необходимость обязательных изображений
            'upDate' => $this->integer()->notNull(),
            'description' => $this->string()
        ]);
```
- для описаний стоит использовать тип `text` - у _string_ ограничение 255 символов по умолчанию. А описание будет намного больше. 

PHP
------------
- в моделе brand отсутствует упоминанние опции `slug`. Если в правилах опция не описана, она и не будет сохраняться в базу даже если её загрузить в модель. 
Кстати, в Yii2 есть понятие `dirtyAttributes` - это атрибуты, которые были изменены. Только они и будут сохраняться. При создании нового объекта все атрибуты попадают под это понятие; при изменении - только те, которые были изменены. В этот набор попадают только те атрибуты, которые описаны в правилах. [Подробнее тут](https://www.yiiframework.com/doc/guide/2.0/ru/db-active-record#dirty-attributes).
- в последних верися Yii2 метод `@className()` числится устаревшим. Используйте стандартное для PHP `::class`.
- внутренности папки для загрузок должны быть включены в gitignore. Но сама папка должна присутствовать в git. _По аналогии с runtime и assets_
- В Yii есть виджет, который генерирует меню. Вместо меню, которое есть на некоторых страницах, сразу добавить все разделы сайта в гравное меню в лайаут `main.php`. Там есть переменная `$menuItems`, которая включает в себя все ссылки - вот туда и перемести свои ссылки. И Отдельного лайаута `mytheme.php` отпадёт надобность. _Главное меню в админке должно быть доступно на всех страницах_

**Comment by mubat** [comment]
Yii
------
- неправильное описание роута: `'<controller:w+>/<action:w+>/<id:d+>' => '<controller>/<action>',` - посмотри на [примеры в руководстве](https://www.yiiframework.com/doc/guide/2.0/en/runtime-routing#url-rules) и внимательно на свою реализацию
- `Url::to(['brand/'])]` - можно и так (должно работать), но я обычно пишу `['brand/index']` для наглядности
- Ссылки в backend/views/layouts/main.php:$menuItems не обязательно через `Url::to()` генерировать - виджет `Nav`, в который они передаются, сам вызывает `Url::to()`.
- был коммит, где вместо `::className()` указывались `::class()` - разве не писало ошибку? Если писало, то не надо было комитить завеедомо ошибочный код.
- непонятно, для чего добавил _.gitgnore_ в папку с лайаутами - так в git остались ненужные файлы, да еще и невидимые git. Стоило эти файлы удалить за ненадобностью.
- метод `BrandController::actionShowdb()` лишний. Для чего он нужен, если есть `actionIndex()`, который выводит все записи?
- Если `Brand::upDate` - это для указания даты, то не нужно его выводить в форме для заполнения; вывод значения на _view_ и _index_ страницах должен быть в формате `datetime`
- Поле `Brand::img` будет для хранения изображения - его так же не нужно выводить на форме.
