### ISSUE TITLE
Создание сущности Автомобиль

### ISSUE THREAD

**Issue by mubat** [andrkyn/autoandev#4]
Создать в базе таблицу Автомобиль со следующими полями:

1. Название
1. Объём двигателя
1. год выпуска
1. ID Марки автомобиля.
1. текстовое поле для описания
1. дату создания записи
1. дату изменения записи.

Создать соответствующую Active Record модель, контроллер, и CRUD страницы для сущности в backend.

Связать таблицы Автомобиля и Марки автомобиля через внешние ключи и соответсвующие правила в моделе. На index и view страницах должны выводиться названия Марок автомобилей. 

Реализацию выполнить в отдельной ветке git.

**Comment by andrkyn** [comment]
Добавил ветку "dev_car", перешел на неё. Контроллер, модель, CRUD заново не создавал, т.к. были созданы ранее. Внёс исправления, согласно заданию на текущем этапе. Удалил из-зи недабности файл миграции **m180507_112740_rename_column_category.php** , т.к. уже не предполагается переименовывать колонку upDate в date в сущьности "Автомобиль".
